:backgroundrb:
    :port: 11006
    :ip: 127.0.0.1
    :environment: production
    :log: foreground
    :debug_log: true
    :persistent_disabled: true
    :persistent_delay: 10  
:schedules:
    :auto_grade_monitor_worker:
        :free_in_service:
            :trigger_args:
                :start: <%= Time.now %>
                :trigger_args: 0 * */2 * * *
        :check_queue:
            :trigger_args:
                :start: <%= Time.now %>
                :trigger_args: 0,10,20,30,40,50 * * * * *
