
monitor:    
    :class: :auto_grade_monitor_worker
    :job_key: :auto_grade_monitor
    :worker_method: :do_work
    :trigger_args:
        :start: <%= Time.now + 10.seconds %>

#requeue:
#    :class: :grade_re_queue_worker
#    :job_key: :requeue_monitor
#    :worker_method: :do_work
#    :trigger_args:
#        :start: <%= Time.now + 60.seconds %>

#monitor:
#    :class: :auto_grade_monitor_worker
#    :trigger_args: 0,15,30,45 * * * * * *
    
#requeue:
#    :class: :grade_re_queue_worker
#    :trigger_args: 0 * * * * * *