version: 0.2.12 (Someday) 20070124
title: Miami University Computer Science

organization: Miami University

email: mike.helmick@muohio.edu
blackboard: http://mymiami.muohio.edu
dir_link: http://netapps.muohio.edu/phpapps/directory/?searchstring=


#external_dir: /Users/Shared/courseware
external_dir: /srv/www/rails/cscourseware/shared/storage

temp_dir: /tmp

# session limit
session_limit: 1800

# number of recent items to show
recent_items: 25

# enscript for code formatting
enscript_command: /usr/bin/enscript

# Require the 1.3 client - for it's XML output capabilities
subversion_command: /usr/local/bin/svn

# either ldap or basic
#authtype: basic
authtype: ldap
# the setting below need to be filled in if LDAP is being used
#ldapserver: 127.0.0.1
ldapserver: ldapsun1.muohio.edu
ldap_dc: dc=muohio,dc=edu
ldap_ou: ou=people
ldap_search: uid

ldap_port: 389
# 4001
# 389
# 636
ldap_ssl: false

ldap_field_uid: uid
ldap_field_nickname: eduPersonNickname
ldap_field_firstname: givenName
ldap_field_middlename: muohioeduMiddleName
ldap_field_lastname: sn
ldap_field_affiliation: muohioeduAffiliation
ldap_field_personaltitle: personalTitle
ldap_field_email: mail
ldap_field_officehours: muohioeduHours 
ldap_field_phone: telephoneNumber

instructor_affiliation: Faculty

# auto enroll
# Must have LDAP enabled & this info must be available via LDAP
enable_auto_enroll: true

ldap_faculty_crn: muohioeduCurrentTeachingCRN
ldap_faculty_desc: muohioeduCurrentTeachingSubjectNumber
ldap_student_crn: muohioeduCurrentCourseCRN
ldap_student_desc: muohioeduCurrentCourseSubjectNumber
## our format is Year Term(2 digit) and a 5 digit course number
## with the first 6 digits fully identifying the term
## Any format of Y T N will work, but you can disable auto enrol or customize
crn_format: YYYYTTNNNNN

default_subjects: CSA MTH MIS IMS 

## Daily Turn-in limit
turnin_limit: 3
# SET BACK TO 3



## Auto Grading
# PRODUCTION
ruby: /usr/local/bin/ruby
java: /usr/lib/java/bin/java
javac: /usr/lib/java/bin/javac
ant: /usr/bin/ant

# DEVELOPMENT
#ruby: /usr/local/bin/ruby
#java: /usr/bin/java 
#javac: /usr/bin/javac
#ant: /usr/bin/ant

pmd_main: edu.muohio.csa.cscourseware.CheckStyle
pmd_libs:
    - jakarta-oro-2.0.8.jar
    - jaxen-1.1-beta-10.jar
    - pmd-3.8.jar
    - xercesImpl-2.6.2.jar
    - xmlParserAPIs-2.6.2.jar
    - checkStyle.jar
    
banned_java:
    - java.io.File
    - java.io.FileInputStream
    - java.io.FileOutputStream
    - java.io.FileReader
    - java.io.FileWriter
    - System.setIn
    - System.setOut
    - System.setErr
    - System.loadLibrary
    - System.setSecurityManager
    - System.load
    - Runtime.getRuntime
    - java.io.*;
